---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: sipeed-lichee-rv-kernel
summary: A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 20
description: |
  A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 20

adopt-info: kernel
build-base: core20
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on:
      - amd64
      - riscv64
    run-on: riscv64

parts:
  kernel:
    plugin: x-kernel
    source: https://github.com/smaeul/linux.git
    source-branch: riscv/d1-wip
    source-depth: 1
    kernel-compiler: ${SNAPCRAFT_ARCH_TRIPLET}-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-device-trees:
      - allwinner/sun20i-d1-lichee-rv-dock
    kdefconfig:
      - nezha_defconfig
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_NLS_ISO8859_1=y
      - CONFIG_DRM_SUN4I=y
      - CONFIG_DRM_SUN8I_DW_HDMI=y
      - CONFIG_DRM_SUN8I_MIXER=y
      # Disable unneeded modules
      - CONFIG_DRM_RADEON=n
      - CONFIG_DRM_NOUVEAU=n
      - CONFIG_DRM_VIRTIO_GPU=n
      - CONFIG_DRM_AMDGPU=n
      - CONFIG_DRM_MXSFB=n
      - CONFIG_DRM_QXL=n
      - CONFIG_DRM_MGAG200=n
      - CONFIG_DRM_VKMS=n
      - CONFIG_DRM_BOCHS=n
      - CONFIG_DRM_ARCPGU=n
      - CONFIG_DRM_GM12U320=n
      - CONFIG_DRM_CIRRUS_QEMU=n
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/sources/uc-initrd_20-stable_riscv64.snap ${SNAPCRAFT_PART_BUILD}/uc-initrd_20-stable_riscv64.snap
      snapcraftctl build
      VER="$(strings vmlinux|grep "Linux version 5"|cut -d' ' -f3)"
      snapcraftctl set-version "$VER"
    build-packages:
      - dpkg-dev
      - flex
      - bison
      - binutils
      - libssl-dev
      - libfdt-dev
      - cpio
      - binutils-${SNAPCRAFT_ARCH_TRIPLET}
      - device-tree-compiler
      - libelf-dev
      - u-boot-tools
      - on riscv64:
        - gcc
      - else:
        - gcc-${SNAPCRAFT_ARCH_TRIPLET}
    stage:
      - -modules

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    stage:
      - -usr
    organize:
      lib/firmware: firmware

  wlan-driver:
    after: [kernel]
    plugin: nil
    source: https://github.com/lwfinger/rtl8723ds.git
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    override-build: |
      KVER=$(ls ${SNAPCRAFT_PROJECT_DIR}/parts/kernel/install/modules/ | cut -f1 -d/)
      make CROSS_COMPILE="${SNAPCRAFT_ARCH_TRIPLET}-" \
        KSRC="${SNAPCRAFT_PROJECT_DIR}/parts/kernel/build" \
        ARCH="riscv" KVER=${KVER}
      cp ${SNAPCRAFT_PART_BUILD}/8723ds.ko ${SNAPCRAFT_PART_INSTALL}/
    stage:
      - -modules

  depmod:
    plugin: nil
    after:
      - kernel
      - wlan-driver
    override-build: |
      KVER=$(ls ${SNAPCRAFT_PROJECT_DIR}/parts/kernel/install/modules/ | cut -f1 -d/)

      # Collect all kernel and separately built modules
      cp -r ${SNAPCRAFT_PROJECT_DIR}/parts/kernel/install/modules \
        ${SNAPCRAFT_PART_INSTALL}/
      cp -r ${SNAPCRAFT_PROJECT_DIR}/parts/wlan-driver/install/8723ds.ko \
        ${SNAPCRAFT_PART_INSTALL}/modules/${KVER}/

      ln -rs ${SNAPCRAFT_PART_INSTALL} ${SNAPCRAFT_PART_INSTALL}/lib
      depmod -b ${SNAPCRAFT_PART_INSTALL} ${KVER}
    stage:
      - modules

  wlan-firmware:
    plugin: dump
    source: git@github.com:armbian/firmware.git
    organize:
      "*": firmware/
    stage:
      - firmware/rtl_bt/rtl8723ds_*.bin
