---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: sipeed-lichee-rv-kernel
summary: A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 22
description: |
  A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 22

adopt-info: version
build-base: core22
grade: stable
confinement: strict
type: kernel
compression: lzo

architectures:
  - build-on:
      - riscv64
    build-for:
      - riscv64

package-repositories:
  - type: apt
    ppa: itrue/rtl8723bt-firmware

parts:
  kernel:
    plugin: nil
    stage-packages:
      - linux-image-allwinner
      - linux-headers-allwinner
    organize:
      boot/vmlinuz*: vmlinuz
      lib/modules/*: kernel-modules/
      lib/firmware/*/device-tree: dtbs
    stage:
      - dtbs
      - kernel-modules
      - vmlinuz
      - usr/src
    prime:
      - -*

  initrd:
    after:
      - kernel
    plugin: nil
    source: initrd
    build-packages:
      - lz4
      - zstd
      - kmod
    override-build: |
      KVER="$(basename ${CRAFT_STAGE}/kernel-modules/*-allwinner | cut -f1 -d/)"

      # Just use a core20 initrd for now
      lz4cat ${CRAFT_PART_BUILD}/uc-initrd_20-stable_${CRAFT_TARGET_ARCH}.img | cpio -idm
      rm ${CRAFT_PART_BUILD}/uc-initrd_20-stable_${CRAFT_TARGET_ARCH}.img

      # Add module(s) necessary for booting
      install -Dm0644 ${CRAFT_STAGE}/kernel-modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko \
        -t ${CRAFT_PART_BUILD}/lib/modules/${KVER}/kernel/fs/nls

      depmod -b ${CRAFT_PART_BUILD} ${KVER}

      # Update module autoload configuration
      echo "nls_iso8859-1" > ${CRAFT_PART_BUILD}/usr/lib/modules-load.d/ubuntu-core-initramfs.conf

      find . | cpio -o -H newc -R 0:0 | zstd -T0 > ${CRAFT_PART_INSTALL}/initrd.img
    stage:
      - initrd.img
    prime:
      - -*

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
      - firmware-realtek-rtl8723-bt
    organize:
      lib/firmware: firmware
    stage:
      - -usr
      - -lib
      # Remove large firmware files that will never be used
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/moxa
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
      - -firmware/ath3k-1.fw
      - -firmware/qca/htbtfw20.tlv
      - -firmware/qcom
      - -firmware/s5p*
      - -firmware/ath11k
      - -firmware/ath10k
      - -firmware/brcm
      - -firmware/vsc
      - -firmware/cypress

  wlan-driver:
    after:
      - kernel
    plugin: nil
    source: https://git.launchpad.net/ubuntu/+source/licheerv-rtl8723ds-dkms
    source-type: git
    source-depth: 1
    source-branch: applied/ubuntu/devel
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
      - ARCH: "riscv"
    build-packages:
      - make
      - ccache
      - gcc
    override-build: |
      KVER="$(basename ${CRAFT_STAGE}/kernel-modules/*-allwinner | cut -f1 -d/)"

      make KSRC="${CRAFT_STAGE}/usr/src/linux-headers-${KVER}" -j $(nproc) \
        modules

      install -Dm0644 ${CRAFT_PART_BUILD}/8723ds.ko \
        -t ${CRAFT_PART_INSTALL}/kernel-modules/${KVER}/dkms/
    prime:
      - -*

  depmod:
    plugin: nil
    after:
      - kernel
      - wlan-driver
    build-packages:
      - kmod
    override-build: |
      KVER="$(basename ${CRAFT_STAGE}/kernel-modules/*-allwinner | cut -f1 -d/)"

      # Collect all kernel and separately built modules
      cp -ar ${CRAFT_STAGE}/kernel-modules \
        ${CRAFT_PART_INSTALL}/modules

      ln -frs ${CRAFT_PART_INSTALL} ${CRAFT_PART_INSTALL}/lib
      depmod -b ${CRAFT_PART_INSTALL} ${KVER}

  overlays:
    plugin: nil
    source: overlays
    build-packages:
      - device-tree-compiler
    override-build: |
      for f in $(ls ${CRAFT_PART_SRC}/*.dts); do
        dtc -@ -I dts -O dtb -o ${CRAFT_PART_INSTALL}/$(basename $f | cut -f1 -d.).dtbo $f
      done
    organize:
      "*.dtbo": dtbs/overlays/
    stage:
      - dtbs/overlays
    prime:
      - -*

  fit-image:
    after:
      - kernel
      - initrd
      - overlays
    plugin: nil
    source: fit-image
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage \
          -f kernel_${CRAFT_TARGET_ARCH}.its \
          -r ${CRAFT_PART_INSTALL}/kernel.img

  version:
    plugin: nil
    after:
      - kernel
    override-build: |
      KVER="$(basename ${CRAFT_STAGE}/kernel-modules/*-allwinner | cut -f1 -d/)"
      craftctl set version="${KVER}"
      craftctl set grade="devel"
