---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: sipeed-lichee-rv-kernel
summary: A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 20
description: |
  A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 20

adopt-info: kernel
build-base: core20
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on:
      - amd64
      - riscv64
    run-on: riscv64

parts:
  kernel:
    plugin: x-kernel
    source: https://github.com/AlexGhiti/riscv-linux.git
    source-branch: int/alex/nezha_wifi_Ubuntu-unstable-5.17.0-8.8
    source-depth: 1
    kernel-compiler: ${SNAPCRAFT_ARCH_TRIPLET}-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-device-trees:
      - allwinner/sun20i-d1-lichee-rv-dock
    kconfigflavour: generic
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_DEBUG_INFO_BTF=n
      - CONFIG_DEBUG_INFO=n
      - CONFIG_NLS_ISO8859_1=y
    override-pull: |
      snapcraftctl pull
      patch -p1 < ${SNAPCRAFT_PROJECT_DIR}/0001-memory.patch
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/sources/uc-initrd_20-stable_riscv64.snap ${SNAPCRAFT_PART_BUILD}/uc-initrd_20-stable_riscv64.snap
      snapcraftctl build
      VER="$(strings vmlinux|grep "Linux version 5"|cut -d' ' -f3)"
      snapcraftctl set-version "$VER"
    build-packages:
      - dpkg-dev
      - flex
      - bison
      - binutils
      - libssl-dev
      - libfdt-dev
      - cpio
      - binutils-${SNAPCRAFT_ARCH_TRIPLET}
      - device-tree-compiler
      - libelf-dev
      - u-boot-tools
      - on riscv64:
        - gcc
      - else:
        - gcc-${SNAPCRAFT_ARCH_TRIPLET}
    stage:
      - -kernel.img
    prime:
      - -initrd.img
      - -dtbs/
  fit-image:
    after:
      - kernel
    plugin: nil
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage \
          -f ${SNAPCRAFT_PROJECT_DIR}/fitimage.its \
          -r ${SNAPCRAFT_PART_INSTALL}/kernel.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    stage:
      - -usr
    organize:
      lib/firmware: firmware
