---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: sipeed-lichee-kernel
summary: A Sipeed Lichee BSP board kernel for use with Ubuntu Core 20
description: |
  A Sipeed Lichee BSP board kernel for use with Ubuntu Core 20

adopt-info: kernel
build-base: core20
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on:
      - amd64
      - riscv64
    run-on: riscv64

parts:
  kernel:
    plugin: x-kernel
    source: https://github.com/AlexGhiti/riscv-linux.git
    source-branch: int/alex/nezha_wifi_Ubuntu-unstable-5.17.0-8.8
    source-depth: 1
    kconfigflavour: generic
    kernel-compiler: ${SNAPCRAFT_ARCH_TRIPLET}-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-device-trees: [allwinner/sun20i-d1-lichee-rv-dock]
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_DEBUG_INFO=n
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/sources/uc-initrd_20-stable_riscv64.snap ${SNAPCRAFT_PART_BUILD}/uc-initrd_20-stable_riscv64.snap
      snapcraftctl build
      # Extract version from Debian changelog
      snapcraftctl set-version $(head -n1 ${SNAPCRAFT_PART_SRC}/debian.riscv/changelog | cut -f2 -d\( | cut -f1 -d\))
    build-packages:
      - dpkg-dev
      - flex
      - bison
      - binutils
      - libssl-dev
      - libfdt-dev
      - cpio
      - device-tree-compiler
      - libelf-dev
      - u-boot-tools
      - dwarves
      - on riscv64:
          - gcc
          - binutils
      - else:
          - gcc-${SNAPCRAFT_ARCH_TRIPLET}
          - binutils-${SNAPCRAFT_ARCH_TRIPLET}

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    stage:
      - -usr
    organize:
      lib/firmware: firmware
