name: visionfive-kernel
summary: A VisionFife BSP board kernel for use with Ubuntu Core 20
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

adopt-info: kernel
build-base: core20
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on:
    - amd64
    - riscv64
    run-on: riscv64

parts:
  firmware:
    plugin: nil
    source: git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
    source-depth: 1
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/firmware
      cp -av ./* $SNAPCRAFT_PART_INSTALL/firmware/
  xtra-fw:
    plugin: nil
    override-build: |
      svn checkout https://github.com/starfive-tech/linux/branches/visionfive-5.17.y/firmware $SNAPCRAFT_PART_INSTALL/firmware
    build-packages:
      - subversion
  kernel:
    plugin: x-kernel
    source: https://github.com/AlexGhiti/riscv-linux.git
    source-branch: int/alex/visionfive_Ubuntu-unstable-5.17.0-8.8
    source-depth: 1
    kernel-compiler: riscv64-linux-gnu-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-device-trees:
      - starfive/jh7100-starfive-visionfive-v1
    kconfigflavour: generic
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_DEBUG_INFO_BTF=n
      - CONFIG_DEBUG_INFO=n
      - CONFIG_NLS_ISO8859_1=y
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/sources/uc-initrd_20-stable_riscv64.snap ${SNAPCRAFT_PART_BUILD}/uc-initrd_20-stable_riscv64.snap
      snapcraftctl build
      VER="$(strings vmlinux|grep "Linux version 5"|cut -d' ' -f3)"
      snapcraftctl set-version "$VER"
    build-packages:
      - dpkg-dev
      - flex
      - bison
      - binutils
      - libssl-dev
      - libfdt-dev
      - cpio
      - binutils-riscv64-linux-gnu
      - device-tree-compiler
      - libelf-dev
      - u-boot-tools
      - on amd64:
        - gcc-riscv64-linux-gnu
      - else:
        - gcc
