---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: sipeed-lichee-rv-kernel
summary: A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 22
description: |
  A Sipeed Lichee RV BSP board kernel for use with Ubuntu Core 22

adopt-info: kernel
build-base: core22
grade: stable
confinement: strict
type: kernel
compression: lzo

architectures:
  - build-on:
      - amd64
      - arm64
      - riscv64
    build-for: riscv64

package-repositories:
  - type: apt
    url: https://ppa.launchpadcontent.net/canonical-kernel-team/ppa/ubuntu
    components: [main]
    architectures: [riscv64]
    key-id: 110E21D8B0E2A1F0243AF6820856F197B892ACEA
    key-server: keyserver.ubuntu.com
    suites: [jammy]
    formats:
      - deb
      - deb-src

parts:
  kernel:
    plugin: nil
    stage-packages:
      - linux-allwinner:${CRAFT_TARGET_ARCH}
    override-stage: |
      craftctl default
      craftctl set version="$(ls ${CRAFT_PART_INSTALL}/kernel-modules/ | cut -f1 -d/)"
      craftctl set grade="devel"
    organize:
      boot/vmlinuz-*: vmlinuz
      boot/config-*: kconfig
      lib/modules: kernel-modules
      lib/firmware/*/device-tree: dtbs
    stage:
      - vmlinuz
      - kernel-modules
      - kconfig
      - dtbs
      # Remove large modules that will never be used
      - -kernel-modules/*/kernel/drivers/net/ethernet
      - -kernel-modules/*/kernel/drivers/gpu/drm/amd
      - -kernel-modules/*/kernel/drivers/gpu/drm/nouveau
      - -kernel-modules/*/kernel/drivers/gpu/drm/radeon
      - -kernel-modules/*/kernel/drivers/scsi
      - -kernel-modules/*/kernel/drivers/media
      - -kernel-modules/*/kernel/drivers/net/can
      - -kernel-modules/*/kernel/drivers/net/dsa
      - -kernel-modules/*/kernel/drivers/net/wireless/ath
      - -kernel-modules/*/kernel/drivers/net/wireless/intel
      - -kernel-modules/*/kernel/drivers/net/wireless/mediatek
      - -kernel-modules/*/kernel/drivers/net/wireless/broadcom
      - -kernel-modules/*/kernel/drivers/net/wireless/marvell
      - -kernel-modules/*/kernel/drivers/net/wireless/ralink
      - -kernel-modules/*/kernel/drivers/net/wireless/intersil
      - -kernel-modules/*/kernel/drivers/net/wireless/ti
      - -kernel-modules/*/kernel/drivers/infiniband
      - -kernel-modules/*/kernel/drivers/sound/pci
      - -kernel-modules/*/kernel/drivers/comedi

    prime:
      - -*

  initrd:
    after:
      - kernel
    plugin: nil
    source: initrd
    build-packages:
      - lz4
      - kmod
    override-build: |
      KVER=$(craftctl get version)

      # Just use a core20 initrd for now
      lz4cat ${CRAFT_PART_BUILD}/uc-initrd_20-stable_${CRAFT_TARGET_ARCH}.img | cpio -idm
      rm ${CRAFT_PART_BUILD}/uc-initrd_20-stable_${CRAFT_TARGET_ARCH}.img

      # Add module(s) necessary for booting
      install -Dm0644 ${CRAFT_STAGE}/kernel-modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko \
        ${CRAFT_PART_BUILD}/lib/modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko

      depmod -b ${CRAFT_PART_BUILD} ${KVER}

      find . | cpio -o -H newc -R 0:0 | lz4 -9 -l > ${CRAFT_PART_INSTALL}/initrd.img
    stage:
      - initrd.img
    prime:
      - -*

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    stage:
      - -usr
      - -lib
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/moxa
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
      - -firmware/ath3k-1.fw
      - -firmware/qca/htbtfw20.tlv
      - -firmware/qcom
      - -firmware/s5p*
      - -firmware/ath11k
      - -firmware/ath10k
      - -firmware/brcm
      - -firmware/vsc
      - -firmware/cypress


  kernel-sources:
    after:
      - kernel
    plugin: nil
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    override-build: |
      KVER=$(craftctl get version)
      apt-get source linux-headers-${KVER}:${CRAFT_TARGET_ARCH}
      # Fix missing x permission
      chmod a+x ${CRAFT_PART_BUILD}/linux-allwinner-*/scripts/pahole-version.sh
      rm -f ${CRAFT_PART_BUILD}/linux-allwinner-*.{dsc,tar.*,diff.*}
      cp -r ${CRAFT_PART_BUILD}/linux-allwinner-* ${CRAFT_PART_INSTALL}/kernel-sources

      make -C ${CRAFT_PART_INSTALL}/kernel-sources ARCH=riscv \
        CROSS_COMPILE=${CRAFT_ARCH_TRIPLET}- mrproper
      cp ${CRAFT_STAGE}/kconfig ${CRAFT_PART_INSTALL}/kernel-sources/.config
      make -C ${CRAFT_PART_INSTALL}/kernel-sources ARCH=riscv \
        CROSS_COMPILE=${CRAFT_ARCH_TRIPLET}- -j$(nproc) modules_prepare
    prime:
      - -*

  wlan-driver:
    after:
      - kernel-sources
    plugin: nil
    source: https://github.com/lwfinger/rtl8723ds.git
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    build-packages:
      - gcc-${CRAFT_ARCH_TRIPLET}
    override-build: |
      KVER=$(craftctl get version)

      make CROSS_COMPILE="${CRAFT_ARCH_TRIPLET}-" -j$(nproc) \
        KSRC="${CRAFT_STAGE}/kernel-sources" \
        ARCH="riscv" KVER=${KVER} USER_MODULE_NAME="rtl8723ds"
      cp ${SNAPCRAFT_PART_BUILD}/rtl8723ds.ko ${SNAPCRAFT_PART_INSTALL}/
    stage:
      - rtl8723ds.ko
    prime:
      - -*

  depmod:
    plugin: nil
    after:
      - kernel
      - wlan-driver
    build-packages:
      - kmod
    override-build: |
      KVER=$(craftctl get version)

      # Collect all kernel and separately built modules
      cp -r ${CRAFT_STAGE}/kernel-modules \
        ${CRAFT_PART_INSTALL}/modules
      install -Dm0644 ${CRAFT_STAGE}/rtl8723ds.ko \
        ${CRAFT_PART_INSTALL}/modules/${KVER}/kernel/drivers/net/wireless/realtek/rtl8723ds/rtl8723ds.ko

      ln -rs ${CRAFT_PART_INSTALL} ${CRAFT_PART_INSTALL}/lib
      depmod -b ${CRAFT_PART_INSTALL} ${KVER}

  wlan-firmware:
    plugin: dump
    source: https://github.com/armbian/firmware.git
    organize:
      rtl_bt/rtl8723ds_*.bin: firmware/rtl_bt/
    stage:
      - firmware/rtl_bt

  overlays:
    plugin: nil
    source: overlays
    build-packages:
      - device-tree-compiler
    override-build: |
      for f in $(ls ${CRAFT_PART_SRC}/*.dts); do
        dtc -@ -I dts -O dtb -o ${CRAFT_PART_INSTALL}/$(basename $f | cut -f1 -d.).dtbo $f
      done
    organize:
      "*.dtbo": dtbs/overlays/
    stage:
      - dtbs/overlays
    prime:
      - -*

  fit-image:
    after:
      - kernel
      - initrd
      - overlays
    plugin: nil
    source: fit-image
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage \
          -f kernel_${SNAPCRAFT_TARGET_ARCH}.its \
          -r ${SNAPCRAFT_PART_INSTALL}/kernel.img
